
export default [
    {
        name: 'Liu Bei',
        country: 'Shu',
        health: 4,
        gender: 'M',
        isMonarch: true,
    },
    {
        name: 'Guan Yu',
        country: 'Shu',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Zhang Fei',
        country: 'Shu',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Zhuge Liang',
        country: 'Shu',
        health: 3,
        gender: 'M',
    },
    {
        name: 'Zhao Yun',
        country: 'Shu',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Ma Chao',
        country: 'Shu',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Huang Yue Ying',
        country: 'Shu',
        health: 3,
        gender: 'F',
    },
    {
        name: 'Sun Quan',
        country: 'Wu',
        health: 4,
        gender: 'M',
        isMonarch: true,
    },
    {
        name: 'Gan Ning',
        country: 'Wu',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Lu Meng',
        country: 'Wu',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Huang Gai',
        country: 'Wu',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Zhou Yu',
        country: 'Wu',
        health: 3,
        gender: 'M',
    },
    {
        name: 'Da Qiao',
        country: 'Wu',
        health: 3,
        gender: 'F',
    },
    {
        name: 'Lu Xun',
        country: 'Wu',
        health: 3,
        gender: 'M',
    },
    {
        name: 'Sun Shang Xiang',
        country: 'Wu',
        health: 3,
        gender: 'F',
    },
    {
        name: 'Cao Cao',
        country: 'Wei',
        health: 4,
        gender: 'M',
        isMonarch: true,
    },
    {
        name: 'Sima Yi',
        country: 'Wei',
        health: 3,
        gender: 'M',
    },
    {
        name: 'Xiahou Dun',
        country: 'Wei',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Zhang Liao',
        country: 'Wei',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Xu Chu',
        country: 'Wei',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Guo Jia',
        country: 'Wei',
        health: 3,
        gender: 'M',
    },
    {
        name: 'Zhen Ji',
        country: 'Wei',
        health: 3,
        gender: 'F',
    },
    {
        name: 'Hua Tuo',
        country: 'Kingdomless',
        health: 3,
        gender: 'M',
    },
    {
        name: 'Diao Chan',
        country: 'Kingdomless',
        health: 3,
        gender: 'F',
    },
    {
        name: 'Lu Bu',
        country: 'Kingdomless',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Wei Yan',
        country: 'Shu',
        health: 4,
        gender: 'M',
        expansion: 'wind',
    },
    {
        name: 'Huang Zhong',
        country: 'Shu',
        health: 4,
        gender: 'M',
        expansion: 'wind',
    },
    {
        name: 'Xiahou Yuan',
        country: 'Wei',
        health: 4,
        gender: 'M',
        expansion: 'wind',
    },
    {
        name: 'Cao Ren',
        country: 'Wei',
        health: 4,
        gender: 'M',
        expansion: 'wind',
    },
    {
        name: 'Zhou Tai',
        country: 'Wu',
        health: 4,
        gender: 'M',
        expansion: 'wind',
    },
    {
        name: 'Xiao Qiao',
        country: 'Wu',
        health: 3,
        gender: 'F',
        expansion: 'wind',
    },
    {
        name: 'Zhang Jiao',
        country: 'Kingdomless',
        health: 3,
        gender: 'M',
        expansion: 'wind',
        isMonarch: true,
    },
    {
        name: 'Yu Ji',
        country: 'Kingdomless',
        health: 3,
        gender: 'M',
        expansion: 'wind',
    },
    {
        name: 'Zhuge Liang 8',
        country: 'Shu',
        health: 3,
        gender: 'M',
        expansion: 'fire',
    },
    {
        name: 'Pang Tong',
        country: 'Shu',
        health: 3,
        gender: 'M',
        expansion: 'fire',
    },
    {
        name: 'Dian Wei',
        country: 'Wei',
        health: 4,
        gender: 'M',
        expansion: 'fire',
    },
    {
        name: 'Xun Yu',
        country: 'Wei',
        health: 3,
        gender: 'M',
        expansion: 'fire',
    },
    {
        name: 'Tai Shi Ci',
        country: 'Wu',
        health: 4,
        gender: 'M',
        expansion: 'fire',
    },
    {
        name: 'Yuan Shao',
        country: 'Kingdomless',
        health: 4,
        gender: 'M',
        expansion: 'fire',
        isMonarch: true,
    },
    {
        name: 'Pang De',
        country: 'Kingdomless',
        health: 4,
        gender: 'M',
        expansion: 'fire',
    },
    {
        name: 'Yan Liang Wen Chou',
        country: 'Kingdomless',
        health: 4,
        gender: 'M',
        expansion: 'fire',
    },
    {
        name: 'Meng Huo',
        country: 'Shu',
        health: 4,
        gender: 'M',
        expansion: 'wood',
    },
    {
        name: 'Zhu Rong',
        country: 'Shu',
        health: 4,
        gender: 'F',
        expansion: 'wood',
    },
    {
        name: 'Xu Huang',
        country: 'Wei',
        health: 4,
        gender: 'M',
        expansion: 'wood',
    },
    {
        name: 'Cao Pi',
        country: 'Wei',
        health: 3,
        gender: 'M',
        expansion: 'wood',
        isMonarch: true,
    },
    {
        name: 'Sun Jian',
        country: 'Wu',
        health: 4,
        gender: 'M',
        expansion: 'wood',
    },
    {
        name: 'Lu Su',
        country: 'Wu',
        health: 3,
        gender: 'M',
        expansion: 'wood',
    },
    {
        name: 'Dong Zhuo',
        country: 'Kingdomless',
        health: 8,
        gender: 'M',
        expansion: 'wood',
        isMonarch: true,
    },
    {
        name: 'Jia Xu',
        country: 'Kingdomless',
        health: 3,
        gender: 'M',
        expansion: 'wood',
    },
    {
        name: 'Hua Xiong',
        country: 'Kingdomless',
        health: 6,
        gender: 'M',
    },
    {
        name: 'Yuan Shu',
        country: 'Kingdomless',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Zhang He',
        country: 'Wei',
        health: 4,
        gender: 'M',
        expansion: 'hills',
    },
    {
        name: 'Deng Ai',
        country: 'Wei',
        health: 4,
        gender: 'M',
        expansion: 'hills',
    },
    {
        name: 'Jiang Wei',
        country: 'Shu',
        health: 4,
        gender: 'M',
        expansion: 'hills',
    },
    {
        name: 'Liu Shan',
        country: 'Shu',
        health: 3,
        gender: 'M',
        expansion: 'hills',
        isMonarch: true,
    },
    {
        name: 'Sun Ce',
        country: 'Wu',
        health: 4,
        gender: 'M',
        expansion: 'hills',
        isMonarch: true,
    },
    {
        name: 'Zhang Zhao & Zhang Hong',
        country: 'Wu',
        health: 3,
        gender: 'M',
        expansion: 'hills',
    },
    {
        name: 'Cai Wen Ji',
        country: 'Kingdomless',
        health: 3,
        gender: 'F',
        expansion: 'hills',
    },
	{
        name: 'Cao Zhi',
        country: 'Wei',
        health: 3,
        gender: 'M',
        expansion: 'ge1',
    },
	{
        name: 'Gao Shun',
        country: 'Kingdomless',
        health: 4,
        gender: 'M',
        expansion: 'ge1',
    },
	{
        name: 'Chen Gong',
        country: 'Kingdomless',
        health: 3,
        gender: 'M',
        expansion: 'ge1',
    },
	{
        name: 'Fa Zheng',
        country: 'Shu',
        health: 3,
        gender: 'M',
        expansion: 'ge1',
    },
	{
        name: 'Ling Tong',
        country: 'Wu',
        health: 4,
        gender: 'M',
        expansion: 'ge1',
    },
	{
        name: 'Ma Su',
        country: 'Shu',
        health: 3,
        gender: 'M',
        expansion: 'ge1',
    },
	{
        name: 'Wu Guo Tai',
        country: 'Wu',
        health: 3,
        gender: 'F',
        expansion: 'ge1',
    },
	{
        name: 'Xu Sheng',
        country: 'Wu',
        health: 4,
        gender: 'M',
        expansion: 'ge1',
    },
	{
        name: 'Xu Shu',
        country: 'Shu',
        health: 3,
        gender: 'M',
        expansion: 'ge1',
    },
	{
        name: 'Yu Jin',
        country: 'Wei',
        health: 4,
        gender: 'M',
        expansion: 'ge1',
    },
	{
        name: 'Zhang Chun Hua',
        country: 'Wei',
        health: 3,
        gender: 'F',
        expansion: 'ge1',
    },
	{
        name: 'Bu Lianshi',
        country: 'Wu',
        health: 3,
        gender: 'F',
        expansion: 'ge2',
    },
	{
        name: 'Liu Biao',
        country: 'Kingdomless',
        health: 3,
        gender: 'M',
        expansion: 'ge2',
    },
	{
        name: 'Gong Sun Zan',
        country: 'Kingdomless',
        health: 4,
        gender: 'M',
        expansion: 'ge2',
    },
	{
        name: 'Cheng Pu',
        country: 'Wu',
        health: 4,
        gender: 'M',
        expansion: 'ge2',
    },
	{
        name: 'Han Dang',
        country: 'Wu',
        health: 4,
        gender: 'M',
        expansion: 'ge2',
    },
	{
        name: 'Guan Xing & Zhang Bao',
        country: 'Shu',
        health: 4,
        gender: 'M',
        expansion: 'ge2',
    },
	{
        name: 'Liao Hua',
        country: 'Shu',
        health: 4,
        gender: 'M',
        expansion: 'ge2',
    },
	{
        name: 'Ma Dai',
        country: 'Shu',
        health: 4,
        gender: 'M',
        expansion: 'ge2',
    },
	{
        name: 'Wang Yi',
        country: 'Wei',
        health: 3,
        gender: 'F',
        expansion: 'ge2',
    },
	{
        name: 'Zhong Hui',
        country: 'Wei',
        health: 4,
        gender: 'M',
        expansion: 'ge2',
    },
	{
        name: 'Cao Zhang',
        country: 'Wei',
        health: 4,
        gender: 'M',
        expansion: 'ge2',
    },
	{
        name: 'Xun You',
        country: 'Wei',
        health: 3,
        gender: 'M',
        expansion: 'ge2',
    },
	{
        name: 'Cao Chong',
        country: 'Wei',
        health: 3,
        gender: 'M',
        expansion: 'ge3',
    },
	{
        name: 'Guo Huai',
        country: 'Wei',
        health: 4,
        gender: 'M',
        expansion: 'ge3',
    },
	{
        name: 'Man Chong',
        country: 'Wei',
        health: 3,
        gender: 'M',
        expansion: 'ge3',
    },
	{
        name: 'Guan Ping',
        country: 'Shu',
        health: 4,
        gender: 'M',
        expansion: 'ge3',
    },
	{
        name: 'Jian Yong',
        country: 'Shu',
        health: 3,
        gender: 'M',
        expansion: 'ge3',
    },
	{
        name: 'Liu Feng',
        country: 'Shu',
        health: 4,
        gender: 'M',
        expansion: 'ge3',
    },
	{
        name: 'Pan Zhang & Ma Zhong',
        country: 'Wu',
        health: 4,
        gender: 'M',
        expansion: 'ge3',
    },
	{
        name: 'Yu Fan',
        country: 'Wu',
        health: 3,
        gender: 'M',
        expansion: 'ge3',
    },
	{
        name: 'Zhu Ran',
        country: 'Wu',
        health: 4,
        gender: 'M',
        expansion: 'ge3',
    },
	{
        name: 'Empress Fu',
        country: 'Kingdomless',
        health: 3,
        gender: 'F',
        expansion: 'ge3',
    },
	{
        name: 'Li Ru',
        country: 'Kingdomless',
        health: 3,
        gender: 'M',
        expansion: 'ge3',
    },
	{
        name: 'Cao Zhen',
        country: 'Wei',
        health: 4,
        gender: 'M',
        expansion: 'ge4',
    },
	{
        name: 'Han Hao & Shi Huan',
        country: 'Wei',
        health: 4,
        gender: 'M',
        expansion: 'ge4',
    },
	{
        name: 'Chen Qun',
        country: 'Wei',
        health: 3,
        gender: 'M',
        expansion: 'ge4',
    },
	{
        name: 'Wu Yi',
        country: 'Shu',
        health: 4,
        gender: 'M',
        expansion: 'ge4',
    },
	{
        name: 'Zhou Cang',
        country: 'Shu',
        health: 4,
        gender: 'M',
        expansion: 'ge4',
    },
	{
        name: 'Zhang Song',
        country: 'Shu',
        health: 3,
        gender: 'M',
        expansion: 'ge4',
    },
	{
        name: 'Sun Lu Ban',
        country: 'Wu',
        health: 3,
        gender: 'F',
        expansion: 'ge4',
    },
	{
        name: 'Gu Yong',
        country: 'Wu',
        health: 3,
        gender: 'M',
        expansion: 'ge4',
    },
	{
        name: 'Ju Shou',
        country: 'Kingdomless',
        health: 3,
        gender: 'M',
        expansion: 'ge4',
    },
	{
        name: 'Lady Cai',
        country: 'Kingdomless',
        health: 3,
        gender: 'F',
        expansion: 'ge4',
    },
	{
        name: 'Zhu Huan',
        country: 'Wu',
        health: 4,
        gender: 'M',
        expansion: 'ge4',
    },
	{
        name: 'Cao Xiu',
        country: 'Wei',
        health: 4,
        gender: 'M',
        expansion: 'ge5',
    },
	{
        name: 'Cao Rui',
        country: 'Wei',
        health: 3,
        gender: 'M',
        expansion: 'ge5',
		isMonarch: true,
    },
	{
        name: 'Zhong Yao',
        country: 'Wei',
        health: 3,
        gender: 'M',
        expansion: 'ge5',
    },
	{
        name: 'Liu Chen',
        country: 'Shu',
        health: 4,
        gender: 'M',
        expansion: 'ge5',
		isMonarch: true,
    },
	{
        name: 'Xiahou Shi',
        country: 'Shu',
        health: 3,
        gender: 'F',
        expansion: 'ge5',
    },
	{
        name: 'Zhang Yi',
        country: 'Shu',
        health: 4,
        gender: 'M',
        expansion: 'ge5',
    },
	{
        name: 'Sun Xiu',
        country: 'Wu',
        health: 3,
        gender: 'M',
        expansion: 'ge5',
		isMonarch: true,
    },
	{
        name: 'Zhu Zhi',
        country: 'Wu',
        health: 4,
        gender: 'M',
        expansion: 'ge5',
    },
	{
        name: 'Quan Cong',
        country: 'Wu',
        health: 4,
        gender: 'M',
        expansion: 'ge5',
    },
	{
        name: 'Gong Sun Yuan',
        country: 'Kingdomless',
        health: 4,
        gender: 'M',
        expansion: 'ge5',
    },
	{
        name: 'Guo Tu & Feng Ji',
        country: 'Kingdomless',
        health: 3,
        gender: 'M',
        expansion: 'ge5',
    },
];
